ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
