ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_csid.o
