ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
