ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-diego/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
